apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotNET-ewok
  description: Just a regular old vulnerable .NET project
  labels:
    example.com/custom: custom_label_value
  annotations:
    endor.ai/project-id: 65f959bf58ad331f0419bb4d
    github.com/project-slug: TreetopTechie/dotNET-ewok
  tags:
    - dotnet
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: solution-architecture-team
  system: public-websites
